import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f0f0f0",
  },
  form: {
    display: "flex",
    flexDirection: "row",
    paddingHorizontal: 15,
    paddingTop: 15,
    backgroundColor: "#f0f0f0",
  },
  iconColumn: {
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  line: {
    width: 2,
    height: 30,
    backgroundColor: "#000",
    marginVertical: 4,
  },
  inputColumn: {
    flexDirection: "column",
    justifyContent: "center",
    flex: 1,
  },
  input: {
    width: "100%",
    height: 45,
    borderColor: "#ccc",
    borderWidth: 1,
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 12,
    fontSize: 16,
    backgroundColor: "#fff",
    fontFamily: "Righteous",
    color: "#000",
  },
  loadingContainer: {
    textAlign: "center",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f0f0f0",
    borderRadius: 8,
    flexDirection: "column",
    marginBottom: 12,
  },
  loadingText: {
    marginLeft: 10,
    fontSize: 16,
    color: "#000",
    fontFamily: "Righteous",
  },
  mapContainer: {
    flex: 1,
    borderTopWidth: 1,
    borderColor: "#ccc",
  },
  map: {
    flex: 1,
  },
  bottomSheetBackground: {
    backgroundColor: "#f0f0f0",
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderLeftColor: "#ccc",
    borderRightColor: "#ccc",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    borderStartEndRadius: 0,
    borderEndEndRadius: 0,
    borderTopColor: "#ccc",
  },
  handleIndicator: {
    backgroundColor: "#aaa",
    width: 40,
    height: 5,
    alignSelf: "center",
    marginVertical: 5,
    borderRadius: 3,
  },
  bottomSheetContent: {
    padding: 20,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  bottomSheetTitle: {
    fontSize: 22,
    color: "#000",
    fontFamily: "Righteous",
  },
  detailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#ccc",
  },
  detailLabel: {
    fontSize: 16,
    color: "#000",
    fontFamily: "Righteous",
  },
  detailValue: {
    fontSize: 16,
    color: "#000",
    textAlign: "right",
    flexShrink: 1,
    marginLeft: 10,
    fontFamily: "Righteous",
  },
  priceText: {
    color: "#2e7d32",
    fontFamily: "Righteous",
  },
  pickerContainer: {
    marginTop: 15,
    marginBottom: 20,
  },
  pickerLabel: {
    fontSize: 16,
    color: "#000",
    marginBottom: 8,
    fontFamily: "Righteous",
  },
  picker: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 8,
    overflow: "hidden",
  },
  solicitarButton: {
    backgroundColor: "#000",
    padding: 15,
    marginBottom: 20,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  solicitarButtonText: {
    color: "#f0f0f0",
    fontSize: 18,
    fontFamily: "Righteous",
  },
  floatingButton: {
    position: "absolute",
    bottom: 20,
    right: 20,
    backgroundColor: "#000",
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 30,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 3,
  },
  floatingButtonText: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Righteous",
    marginRight: 8,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  saveButton: {
    backgroundColor: "#000",
    padding: 15,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 5,
    marginBottom: 10,
  },
  saveButtonText: {
    color: "#fff",
    fontSize: 16,
    fontFamily: "Righteous",
  },
  comeBack: {
    position: "absolute",
    top: 10,
    left: 10,
    backgroundColor: "#000",
    width: 40,
    height: 40,
    borderRadius: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    elevation: 5,
  },
});

export default styles;