import { StyleSheet, StatusBar } from "react-native";
const styles = StyleSheet.create({
  container: {
    backgroundColor: "#f0f0f0",
    paddingHorizontal: 16,
    paddingTop: StatusBar.currentHeight || 40,
    paddingBottom: 30,
    flex: 1,
  },
  loading: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 20,
  },
  photoContainer: {
    position: "relative",
    marginRight: 16,
  },
  profilePhoto: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#e0e0e0",
  },
  editPhotoButton: {
    position: "absolute",
    bottom: 0,
    right: 0,
    backgroundColor: "#000",
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontFamily: "Righteous",
    fontSize: 24,
    color: "#000",
    marginBottom: 4,
  },
  userEmail: {
    fontFamily: "Righteous",
    fontSize: 14,
    color: "#555",
  },
  userSinceContainer: {
    marginBottom: 12,
    marginTop: 4,
    alignItems: "flex-start",
    justifyContent: "center",
    flexDirection: "row",
    gap: 8,
    flexWrap: "wrap",
    width: "100%",
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 16,
    backgroundColor: "#fff",
    borderRadius: 12,
    elevation: 2,
    alignSelf: "center",
  },
  userSince: {
    fontFamily: "Righteous",
    fontSize: 18,
    color: "#000",
    textAlign: "left",
    marginTop: 4,
  },
  row: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
    width: "100%",
  },
  boxButton: {
    flex: 1,
    backgroundColor: "#fff",
    paddingVertical: 12,
    paddingHorizontal: 10,
    marginHorizontal: 5,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
    gap: 6,
    elevation: 2,
  },
  boxText: {
    fontFamily: "Righteous",
    fontSize: 14,
    color: "#000",
  },
   icon: {
    width: 40,
    height: 40,
    marginBottom: 4,
  },
  iconText: {
    fontFamily: "Righteous",
    fontSize: 16,
    color: "#000",
    textAlign: "center",
  },
  logoutButton: {
    position: "absolute",
    bottom: 20,
    left: 16,
    right: 16,
    backgroundColor: "#DB2E05",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
    borderRadius: 12,
    gap: 8,
  },
  logoutText: {
    fontFamily: "Righteous",
    color: "#fff",
    fontSize: 16,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
  },
  modalContainer: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 32,
  },
  photoModalContainer: {
    backgroundColor: "#fff",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: 24,
    paddingBottom: 32,
    alignItems: "center",
  },
  modalTitle: {
    fontFamily: "Righteous",
    fontSize: 20,
    color: "#000",
    marginBottom: 16,
    textAlign: "center",
  },
  modalMessage: {
    fontFamily: "Righteous",
    fontSize: 16,
    color: "#555",
    textAlign: "center",
    marginBottom: 24,
    lineHeight: 22,
  },
  modalButtonsContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 16,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  photoModalOption: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 16,
    paddingHorizontal: 24,
    width: "100%",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  photoModalOptionText: {
    fontFamily: "Righteous",
    fontSize: 16,
    color: "#000",
    marginLeft: 16,
  },
  cancelButton: {
    backgroundColor: "#f0f0f0",
    borderWidth: 1,
    borderColor: "#ddd",
  },
  confirmButton: {
    backgroundColor: "#DB2E05",
  },
  cancelButtonText: {
    fontFamily: "Righteous",
    fontSize: 16,
    color: "#000",
  },
  confirmButtonText: {
    fontFamily: "Righteous",
    fontSize: 16,
    color: "#fff",
  },
});

export default styles;